#!/usr/bin/env python3
"""Freeze a fixed COCO-replay set so the regression gate can catch catastrophic forgetting.

Copies up to --limit labelled coco128 images (auto-downloaded by Ultralytics when online)
into $STORAGE_DIR/datasets/coco_replay/{images,labels} and writes base.yaml beside them;
train_overnight.py re-validates every candidate against this set before staging it.
Offline, fill the same layout by hand with at least MIN_REPLAY_IMAGES frames whose labels
use raw COCO ids 0-79.

    prep_replay.py [--limit 128] [--force]
"""

import argparse
import os
import shutil
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

import assemble_dataset

REPLAY_ROOT = assemble_dataset.COCO_REPLAY_ROOT
IMAGES_DIR = assemble_dataset.COCO_REPLAY_IMAGES
LABELS_DIR = assemble_dataset.COCO_REPLAY_LABELS
BASE_YAML = assemble_dataset.COCO_REPLAY_YAML

IMG_EXTS = (".jpg", ".jpeg", ".png", ".bmp", ".webp")
MIN_REPLAY_IMAGES = 64


def _img2label(img_path):
    """Map an Ultralytics image path to its YOLO label path."""
    sep = f"{os.sep}images{os.sep}"
    if sep in img_path:
        base = img_path.rsplit(sep, 1)[0] + f"{os.sep}labels{os.sep}" + img_path.rsplit(sep, 1)[1]
    else:
        base = img_path
    return os.path.splitext(base)[0] + ".txt"


def _list_images(directory):
    if not os.path.isdir(directory):
        return []
    return sorted(
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.lower().endswith(IMG_EXTS)
    )


def _source_images():
    """Resolve the coco128 image directory, auto-downloading when online."""
    from ultralytics.data.utils import check_det_dataset

    data = check_det_dataset("coco128.yaml")
    src = data.get("val") or data.get("train")
    if isinstance(src, (list, tuple)):
        src = src[0]
    if src and os.path.isfile(src):
        src = os.path.dirname(src)
    names = data.get("names") or assemble_dataset.coco_names()
    return src, dict(names)


def _write_base_yaml(names):
    lines = [
        "# COCO-replay regression set (auto-generated by prep_replay.py).",
        "# Used by train_overnight.regression_gate to guard base-class mAP.",
        f"path: {REPLAY_ROOT}",
        "train: images",
        "val: images",
        f"nc: {len(names)}",
        "names:",
    ]
    lines.extend(f"  {idx}: {names[idx]}" for idx in sorted(names))
    with open(BASE_YAML, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _is_populated():
    return os.path.isfile(BASE_YAML) and len(_list_images(IMAGES_DIR)) >= MIN_REPLAY_IMAGES


def main():
    parser = argparse.ArgumentParser(description="Freeze a COCO-replay set for the regression gate.")
    parser.add_argument("--force", action="store_true", help="Rebuild even if already populated.")
    parser.add_argument("--limit", type=int, default=128, help="Max images to freeze.")
    args = parser.parse_args()

    assemble_dataset.require_storage_dir()
    os.makedirs(IMAGES_DIR, exist_ok=True)
    os.makedirs(LABELS_DIR, exist_ok=True)

    if _is_populated() and not args.force:
        n = len(_list_images(IMAGES_DIR))
        print(f"[prep_replay] already populated ({n} images) at {REPLAY_ROOT}; use --force to rebuild.")
        return 0

    if args.force:
        for d in (IMAGES_DIR, LABELS_DIR):
            shutil.rmtree(d, ignore_errors=True)
            os.makedirs(d, exist_ok=True)

    src_dir, names = _source_images()
    if not src_dir or not os.path.isdir(src_dir):
        print("[prep_replay] could not obtain coco128 images; offline, fill the replay layout by hand "
              "(see the module docstring).", file=sys.stderr)
        return 1

    images = _list_images(src_dir)[: max(1, args.limit)]
    copied = 0
    for img in images:
        label = _img2label(img)
        if not os.path.isfile(label):
            continue
        shutil.copy2(img, os.path.join(IMAGES_DIR, os.path.basename(img)))
        shutil.copy2(label, os.path.join(LABELS_DIR, os.path.basename(label)))
        copied += 1

    if copied < MIN_REPLAY_IMAGES:
        print(f"[prep_replay] only {copied} labelled images found (< {MIN_REPLAY_IMAGES}); "
              "replay set too small to be a reliable regression gate.", file=sys.stderr)
        return 1

    _write_base_yaml(names)
    print(f"[prep_replay] froze {copied} images + labels into {REPLAY_ROOT}")
    print(f"[prep_replay] wrote {BASE_YAML} (nc={len(names)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
