#!/usr/bin/env python3
"""Freeze a fixed COCO-replay set to fight catastrophic forgetting.

The replay set is a small, stable slice of base-model (COCO 80-class) frames
with their YOLO labels (raw COCO ids 0-79). The overnight regression gate
re-validates the candidate weights against this set so domain adaptation on the
camera footage cannot silently destroy base-class accuracy.

Output layout (SHARED CONTRACT):
    /mnt/storage/visionbox/datasets/coco_replay/
        images/*.jpg
        labels/*.txt        # COCO ids 0-79
        base.yaml           # path/val -> images, names = COCO 0-79
"""

import argparse
import os
import shutil
import sys

REPLAY_ROOT = "/mnt/storage/visionbox/datasets/coco_replay"
IMAGES_DIR = os.path.join(REPLAY_ROOT, "images")
LABELS_DIR = os.path.join(REPLAY_ROOT, "labels")
BASE_YAML = os.path.join(REPLAY_ROOT, "base.yaml")

IMG_EXTS = (".jpg", ".jpeg", ".png", ".bmp", ".webp")
MIN_REPLAY_IMAGES = 64

# Offline fallback (NO network / coco128 unavailable):
# ----------------------------------------------------------------------------
# Curate ~150 high-confidence base-model frames as pseudo-label replay instead.
# Run the current active model over a pool of camera/general frames, keep only
# detections with conf >= 0.85, and write them in YOLO format with RAW COCO ids:
#
#   from visionbox.detector_v2 import load_active
#   model = load_active()
#   for img in sorted(glob.glob("<pool>/*.jpg"))[:150]:
#       res = model(img, conf=0.85, verbose=False)[0]
#       lines = []
#       for b in res.boxes:
#           cls = int(b.cls)                      # already a COCO id 0-79
#           x, y, w, h = b.xywhn[0].tolist()      # normalised cx,cy,w,h
#           lines.append(f"{cls} {x:.6f} {y:.6f} {w:.6f} {h:.6f}")
#       shutil.copy2(img, IMAGES_DIR)
#       write(os.path.join(LABELS_DIR, stem + ".txt"), "\n".join(lines))
#
# Then write base.yaml exactly as _write_base_yaml() does below. Pseudo-labels
# are weaker than coco128's human labels, so prefer the online path whenever a
# network is available.
# ----------------------------------------------------------------------------


def _coco_names():
    """COCO 80-class id->name mapping straight from the base weights."""
    from ultralytics import YOLO

    return dict(YOLO("/home/night/VisionBox/yolov8n.pt").names)


def _img2label(img_path):
    """Map an Ultralytics image path to its YOLO label path."""
    sep = f"{os.sep}images{os.sep}"
    if sep in img_path:
        base = img_path.rsplit(sep, 1)[0] + f"{os.sep}labels{os.sep}" + img_path.rsplit(sep, 1)[1]
    else:
        base = img_path
    stem = os.path.splitext(base)[0]
    return stem + ".txt"


def _list_images(directory):
    if not os.path.isdir(directory):
        return []
    return sorted(
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.lower().endswith(IMG_EXTS)
    )


def _source_images():
    """Resolve the coco128 image directory, auto-downloading when online."""
    from ultralytics.data.utils import check_det_dataset

    data = check_det_dataset("coco128.yaml")
    src = data.get("val") or data.get("train")
    if isinstance(src, (list, tuple)):
        src = src[0]
    if src and os.path.isfile(src):
        src = os.path.dirname(src)
    names = data.get("names") or _coco_names()
    return src, dict(names)


def _write_base_yaml(names):
    lines = [
        "# COCO-replay regression set (auto-generated by prep_replay.py).",
        "# Used by train_overnight.regression_gate to guard base-class mAP.",
        f"path: {REPLAY_ROOT}",
        "train: images",
        "val: images",
        f"nc: {len(names)}",
        "names:",
    ]
    for idx in sorted(names):
        lines.append(f"  {idx}: {names[idx]}")
    with open(BASE_YAML, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _is_populated():
    return (
        os.path.isfile(BASE_YAML)
        and len(_list_images(IMAGES_DIR)) >= MIN_REPLAY_IMAGES
    )


def main():
    parser = argparse.ArgumentParser(description="Freeze a COCO-replay set for the regression gate.")
    parser.add_argument("--force", action="store_true", help="Rebuild even if already populated.")
    parser.add_argument("--limit", type=int, default=128, help="Max images to freeze.")
    args = parser.parse_args()

    os.makedirs(IMAGES_DIR, exist_ok=True)
    os.makedirs(LABELS_DIR, exist_ok=True)

    if _is_populated() and not args.force:
        n = len(_list_images(IMAGES_DIR))
        print(f"[prep_replay] already populated ({n} images) at {REPLAY_ROOT}; use --force to rebuild.")
        return 0

    if args.force:
        for d in (IMAGES_DIR, LABELS_DIR):
            shutil.rmtree(d, ignore_errors=True)
            os.makedirs(d, exist_ok=True)

    src_dir, names = _source_images()
    if not src_dir or not os.path.isdir(src_dir):
        print(
            "[prep_replay] could not obtain coco128 images. If offline, use the "
            "pseudo-label fallback documented at the top of this file.",
            file=sys.stderr,
        )
        return 1

    images = _list_images(src_dir)[: max(1, args.limit)]
    copied = 0
    for img in images:
        label = _img2label(img)
        if not os.path.isfile(label):
            continue
        shutil.copy2(img, os.path.join(IMAGES_DIR, os.path.basename(img)))
        shutil.copy2(label, os.path.join(LABELS_DIR, os.path.basename(label)))
        copied += 1

    if copied < MIN_REPLAY_IMAGES:
        print(
            f"[prep_replay] only {copied} labelled images found (< {MIN_REPLAY_IMAGES}); "
            "replay set too small to be a reliable regression gate.",
            file=sys.stderr,
        )
        return 1

    _write_base_yaml(names)
    print(f"[prep_replay] froze {copied} images + labels into {REPLAY_ROOT}")
    print(f"[prep_replay] wrote {BASE_YAML} (nc={len(names)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
